base_url = "http://localhost:8089"

title = "Kuroshi Catte"
description = """I am Kuroshi. You may also know me as kode54, or Chris Moeller, or my real name, Christopher Snowhill. My character is a literal tuxedo cat, with a tuxedo fur pattern in black and white, with cuff forepaws, and shirt and buttons chest pattern. I came up with this idea for a character with the acquisition of two lovely tuxedo cats, who brighten up my family's daily life and have been with us since December of 2013."""
author = "Christopher Snowhill"

theme = "zallery"

compile_sass = true
generate_feeds = true

taxonomies = [
    {name = "tags", rss = false},
]

[extra]
menu = [
    {url = "atom.xml", name = "Feed"},
    {url = "https://github.com/lscpriv/kuroshizola", name = "Github"},
]

theme_color = "#453145" # color for browser

author_url = "https://kode54.net"
cover_image = "img/cover.webp" # cover image on main gallery pages for opengraph and twitter embeds 

hide_description = false # set to false to show the page description over the thumbnails
hide_copyright = false # set to true to hide the copyright at the bottom of the page
hide_poweredby = false # set to true to hide the poweredby at the bottom of the page

# gallery settings
thumbnail_size = 400 # size in pixels, you may need to adjust the media queries in _gallery.scss
thumbnail_format = "webp" # auto, jpg, png, webp
thumbnail_quality = 90 # value in percentage, only for webp and jpg

# img shortcode settings
covert_images = false # set to true to convert images to to the format in the image_format setting 
create_mobile_images = false # set to true to create mobile friendly versions of the image
image_format = "webp" # auto, jpg, png, webp
image_quality = 90 # value in percentage, only for webp and jpg

# https://modelviewer.dev/
modelviewer = false # set to false to disable loading modelviewer javascript

# https://github.com/francoischalifour/medium-zoom
jszoom = true # set to false to disable javascript based image zoom (will fallback to link to the full image with a button)

# https://www.goatcounter.com/
goatcounter = "kuroshi"
